[FEATURE] Do not compute the full union estiamtion matrix.
seqan/chopper pull request #100
Opened 2022-03-10 08:57 UTC by smehringer

This PR significantly lowers the memory consumption at the cost of performance (not tracked).

Instead of storing all interval union estimations in a matrix of size `#user bins x #user bins` we now only store a single vector of size `#user bins` when computing the current column in the DP algorithm.

2022-03-10 12:34 UTC, eseiler requested changes

2022-03-10 12:34 UTC, eseiler commented on include/chopper/sketch/user_bin_sequence.hpp
> +        estimates.clear();
```suggestion
        estimates.resize(sketches.size());
```

2022-03-10 12:34 UTC, eseiler commented on include/chopper/layout/hierarchical_binning.hpp
> +
```suggestion
```

2022-03-10 12:34 UTC, eseiler commented on include/chopper/layout/hierarchical_binning.hpp
> +            data->union_estimates.resize(num_user_bins);
```suggestion
```

2022-03-11 08:20 UTC, smehringer commented on include/chopper/sketch/user_bin_sequence.hpp
> +        estimates.clear();
You are right. `clear` was stupid. But I don't want to `resize()` everytime and cause memory allocations! I know j is never more than the capacity I allocated beforehand.

2022-03-11 08:37 UTC, smehringer commented on include/chopper/sketch/user_bin_sequence.hpp
> +        estimates.clear();
Actually since I only ever access the values I updated I do not need a resize nor a clear.

2022-03-11 13:08 UTC, eseiler requested changes
Some small assertion stuff.

I find the function names a bit long and hard to understand.

* `compute_interval_union_estimate` -> `interval_union`
* `precompute_interval_union_estimations` -> `row_union`
* `precompute_init_interval_union_estimations` -> `initialise_union`

Other ideas welcome :D

2022-03-11 19:59 UTC, smehringer commented on include/chopper/sketch/user_bin_sequence.hpp
> +    void precompute_interval_union_estimations(std::vector<std::vector<uint64_t>> & estimates, size_t const num_threads) const
mope good point I can throw it away.

2022-03-11 20:15 UTC, smehringer commented
> Some small assertion stuff.
> 
> I find the function names a bit long and hard to understand.
> 
>     * `compute_interval_union_estimate` -> `interval_union`
> 
>     * `precompute_interval_union_estimations` -> `row_union`
> 
>     * `precompute_init_interval_union_estimations` -> `initialise_union`
> 
> 
> Other ideas welcome :D

Hm I still think more verbose names are more helpful but I agree the current ones are not good. I propose:

* precompute_initial_union_estimates(estimates) [computes all unions [0,j] for all j when initialisng the dp matrix]
* precompute_union_estimates_for(estimates, row) [precompute estimates for current j]
* estimate_interval(start, end) [compute a specific interval]

2022-03-13 14:56 UTC, eseiler approved these changes

2022-03-13 14:57 UTC, eseiler commented
Do you want to rebase or squash?

2022-03-13 18:42 UTC, merged