Add factor for needed recursive levels
seqan/chopper pull request #13
Opened 2021-07-11 08:17 UTC by Felix-Droop

I added the level factor from the paper.

The results for the small data sets now have 2 levels instead of 4 and 5.

Some tests fail, but I am not sure whether I broke something or the result is just different/better now.

2021-07-12 11:56 UTC, eseiler requested changes
Some minor things.
We still need to verify that the new results are at least as good as the previous results

2021-07-12 11:56 UTC, eseiler commented on include/chopper/pack/hierarchical_binning.hpp
> +    size_t get_needed_levels(size_t const num_user_bins)
```suggestion
    [[nodiscard]] size_t max_merge_levels(size_t const num_user_bins) const
```
Or some other name?

2021-07-12 11:56 UTC, eseiler commented on include/chopper/pack/hierarchical_binning.hpp
> +    /*!\brief Computes and returns the number of additionally needed recursive levels when doing a merge.
```suggestion
    /*!\brief Returns the maximum number of needed levels when merging `num_user_bins` many user bins.
```
?

2021-07-12 11:56 UTC, eseiler commented on include/chopper/pack/hierarchical_binning.hpp
> +     * \param[in] num_user_bins The number of user bins in the merge
```suggestion
     * \param[in] num_user_bins The number of user bins in the merge.
```

2021-07-12 11:56 UTC, eseiler commented on include/chopper/pack/hierarchical_binning.hpp
> +        return static_cast<size_t>(std::ceil(levels));
I don't know if it would be worth it to store the result of `std::log(num_technical_bins)` as a class member and reuse it here.

2021-07-12 11:56 UTC, eseiler commented on include/chopper/pack/hierarchical_binning.hpp
> +     * \param[in] num_user_bins The number of user bins in the merge
BTW, this "shadows" the class member `num_user_bins`. Can we use another name?

2021-07-12 11:56 UTC, eseiler commented on include/chopper/pack/hierarchical_binning.hpp
> +            size_t sum = 0;
Can you move this definition outside the if/else (you do this line in both branches).

2021-07-12 11:56 UTC, eseiler commented on include/chopper/pack/hierarchical_binning.hpp
>                      // full_score: The score to minimize -> score * #TB-high_level + low_level_memory footprint
Can you add a comment for `ll_kmers`?

2021-07-12 12:06 UTC, eseiler commented on include/chopper/pack/hierarchical_binning.hpp
> +    size_t get_needed_levels(size_t const num_user_bins)
And the function should be in the private block

2021-07-13 09:25 UTC, Felix-Droop commented
I think I applied all the requested changes. Why did the documentation CI fail? I think It says something like `not in gzip format`.

2021-07-13 09:29 UTC, eseiler commented
> I think I applied all the requested changes. Why did the documentation CI fail? I think It says something like `not in gzip format`.

The tests should still fail.
I'll check the tests, then push changes, and fix errors that might arise

2021-07-13 10:03 UTC, merged