[LIB] update hibf lib.
seqan/chopper pull request #223
Opened 2023-10-24 17:38 UTC by smehringer

2023-10-25 13:03 UTC, eseiler requested changes

2023-10-25 13:03 UTC, eseiler commented on src/layout/hibf_statistics.cpp
> +    return std::ceil(
This could call `seqan::hibf::bin_size_in_bits`?

2023-10-25 13:03 UTC, eseiler commented on src/layout/determine_best_number_of_technical_bins.cpp
> +             << "## false positive rate = " << config.hibf_config.maximum_fpr << '\n';
Also print relaxed fpr?

2023-10-26 19:05 UTC, smehringer commented on test/api/display_layout/compute_ibf_size_test.cpp
> +
```suggestion
```

2023-10-27 11:10 UTC, eseiler approved these changes

2023-10-27 11:10 UTC, merged