Statistics of the HIBF layout with --verbose
seqan/chopper pull request #47
Opened 2021-10-10 08:44 UTC by Felix-Droop

- Added the flag `--verbose` that leads to the command line output of additional HIBF statististics. 
- These are generated in the `hibf_model` class. The model is generated during the backtracking of the `hierarchical_binning`.
  - Side remark: Maybe we can move some other parts of the `hierarchical_binning::backtracking` function to the `hibf_model` class to make the code more comprehensible?
- I added a single CLI test for the `--verbose` flag and adjusted the `hierarchical_binning` and `simple_binning` tests.
- While doing this I encountered the bug that the false positive correction is only computed for the number of user bins and not for t_max. I fixed this and also adjusted the tests.

2021-10-10 17:53 UTC, eseiler commented on include/chopper/helper.hpp
> +[[nodiscard]] std::string byte_size_to_formatted_str(size_t bytes)
```suggestion
[[nodiscard]] inline std::string byte_size_to_formatted_str(size_t bytes)
```

2021-10-11 07:16 UTC, smehringer requested changes
First round of some small but major things.

You mentioned that maybe some of the back-tracking could go into the model. I would like to keep the algorithm itself separate from any debug information output.

2021-10-11 07:16 UTC, smehringer commented on include/chopper/pack/hibf_model.hpp
> +    hibf_model & operator=(hibf_model const &) = delete; //!< Defaulted.
```suggestion
    hibf_model & operator=(hibf_model const &) = delete; //!< Deleted.
```

2021-10-11 07:16 UTC, smehringer commented on include/chopper/pack/hierarchical_binning.hpp
> +    hibf_model::ibf * const ibf_model{nullptr};
If this data object is purely to generate some statistics for us, I would not call it `model` as it suggests that it does more. It should be clear that this has nothing to do with the algorithm.

We should rename it to something like `ibf_statistics`, `ibf_stats` or `ibf_debug_info`?

2021-10-11 07:16 UTC, smehringer commented on include/chopper/pack/hierarchical_binning.hpp
> +                         double const query_cost = 0.0) :
Same here. It looks like the hierarchical binning algorithm depends on a model which is confusing.

Can the object live in `pack_data` instead?

2021-10-11 07:16 UTC, smehringer commented on src/chopper_pack.cpp
> +
Do you think that the information are valuable to the user who wants to pack their data?
Or is it rather for us to benchmark the algorithm?

If the former, you can leave the option but if its the latter, I would move this option to the end in the section `special options` (I added sections in some PR that is already merged) and call it `--output-statistics`

2021-10-14 13:41 UTC, closed without merging