[FEATURE] Output detailed statistics if requested.
seqan/chopper pull request #52
Opened 2021-10-12 11:09 UTC by smehringer

follow up of https://github.com/seqan/chopper/pull/47
Closes https://github.com/seqan/chopper/pull/47

- [x] rewrite to shared authorship with Felix

2021-10-13 16:18 UTC, Felix-Droop approved these changes

2021-10-14 09:28 UTC, Felix-Droop requested changes
Changes that make sure that the summary output is sorted by levels.

2021-10-14 09:28 UTC, Felix-Droop commented on include/chopper/pack/hibf_statistics.hpp
> +#include <robin_hood.h>
```suggestion

```

2021-10-14 09:28 UTC, Felix-Droop commented on include/chopper/pack/hibf_statistics.hpp
> +
```suggestion
#include <map>
```

2021-10-14 09:28 UTC, Felix-Droop commented on include/chopper/pack/hibf_statistics.hpp
> +    robin_hood::unordered_map<size_t, level_summary> summary;
```suggestion
    std::map<size_t, level_summary> summary;
```

2021-10-14 09:28 UTC, Felix-Droop commented on include/chopper/pack/hibf_statistics.hpp
> +        for (auto const & [level, s] : summary)
`summary` is an unordered map, so the output is not guaranteed to be sorted by levels. I think it should be, so I suggest changing `summary` to be a simple std::map. The levels are the keys, so it should work by default, I think.

2021-10-14 11:01 UTC, eseiler commented on include/chopper/pack/hibf_statistics.hpp
> +            double const split_tb_percentage = 100 * (double)total_num_split_tbs / (double)total_num_tbs;
Use `static_cast<double>`; in general it should be enough if either of these values is cast to double.

2021-10-14 11:02 UTC, eseiler commented on include/chopper/pack/hibf_statistics.hpp
> +        std::cout << "\n\tStatistics summary:\n\tlevel\tnum_ibfs\tlevel_size\tlevel_size_no_corr\ttotal_num_tbs"
Why prepend a tab?

2021-10-14 11:04 UTC, eseiler commented on include/chopper/pack/hibf_statistics.hpp
> +
Also add a `std::cout << std::fixed << std::setprecision(2)` to only print the first two decimals of doubles?

2021-10-14 11:10 UTC, eseiler commented on include/chopper/pack/hibf_statistics.hpp
> +    std::map<size_t, level_summary> summary;
Couldn't this just be a `std::vector<level_summary>`?
I guess we would need to know how big this will get?

2021-10-14 11:12 UTC, eseiler commented on include/chopper/pack/hibf_statistics.hpp
> +    /*!\brief Computes the bin size.
```suggestion
    /*!\brief Computes the bin size in bits.
```

2021-10-14 11:12 UTC, eseiler commented on include/chopper/pack/hibf_statistics.hpp
> +     * return it as a formatted string with the appropriate unit.
```suggestion
    /*!\brief Compute the Bloom Filter size from `number_of_kmers_to_be_stored` and
     *        return it as a formatted string with the appropriate unit.
```

2021-10-14 11:12 UTC, eseiler commented on include/chopper/pack/hibf_statistics.hpp
> +        return byte_size_to_formatted_str(size);
```suggestion
        size_t const size_in_bytes = compute_bin_size(number_of_kmers_to_be_stored) / 8;
        return byte_size_to_formatted_str(size_in_bytes);
```

2021-10-14 11:13 UTC, eseiler commented on include/chopper/pack/hibf_statistics.hpp
> +    std::map<size_t, level_summary> summary;
```suggestion
    std::map<size_t, level_summary> summaries;
```

2021-10-14 11:14 UTC, eseiler commented on include/chopper/pack/hibf_statistics.hpp
> +        level_summary & s = summary[level];
```suggestion
        level_summary & summary = summaries[level];
```

2021-10-14 11:14 UTC, eseiler commented on include/chopper/pack/hibf_statistics.hpp
> +        for (bin const & b : curr_ibf)
```suggestion
        for (bin const & current_bin : curr_ibf)
```

or similar

2021-10-14 11:17 UTC, eseiler commented on include/chopper/pack/pack_data.hpp
> +    hibf_statistics::ibf * stats{};
```suggestion
    hibf_statistics::ibf * stats{nullptr};
```

This is completely not const, right?

2021-10-14 11:18 UTC, eseiler commented on include/chopper/pack/simple_binning.hpp
> +    pack_data * data{nullptr};
Do we change the pointer?
I can see that we modify the pointee

2021-10-14 11:19 UTC, eseiler commented on test/cli/cli_chopper_pack_statistics_test.cpp
> +#include <seqan3/test/tmp_filename.hpp>
```suggestion
#include <seqan3/test/tmp_filename.hpp>
```

2021-10-14 11:35 UTC, Felix-Droop commented on include/chopper/pack/hibf_statistics.hpp
> +    //!\brief Prints a tab-indented summary of the statistics of this HIBF to the command line
It is actually both tap-seperated and tab-indented. The indentation is done to make the output with `--determine-num-bins` more comprehensible. Should we make this optional, such that it is not indented when the flag is not given and we only have to output a single summary?

2021-10-14 11:35 UTC, smehringer commented on include/chopper/pack/hibf_statistics.hpp
> +    using ibf = std::vector<bin>;
I renamed it to level

2021-10-14 13:32 UTC, eseiler commented on include/chopper/helper.hpp
> +#include <cmath>
```suggestion
#include <cmath>
#include <cstddef>
#include <string>
```

2021-10-14 13:41 UTC, merged