[MISC] Collect estimated query costs in hibf_statistics.
seqan/chopper pull request #81
Opened 2021-11-24 15:15 UTC by smehringer

Now that we understood how the query cost is gathered, I think this refactoring makes it much more easy to understand since the cost is only collected when a split bin is added. 
In the end everything is added up. Done.

2021-11-25 14:11 UTC, eseiler requested changes
data->stats should probably be called data->ibf_statistics or something like that

2021-11-25 14:11 UTC, eseiler commented on include/chopper/layout/hibf_statistics.hpp
> +            double cost = 0.0) :
```suggestion
            double const cost = 0.0) :
```

2021-11-25 14:11 UTC, eseiler commented on include/chopper/layout/hierarchical_binning.hpp
>                  process_merged_bin(libf_data, bin_id, trace_j, j, kmer_count, optimal_score, num_contained_ubs);
```suggestion
                trace_j = next_j; // unneccessary?

                process_merged_bin(libf_data, bin_id, trace_j, j, kmer_count, optimal_score, num_contained_ubs);
```

2021-11-26 07:29 UTC, smehringer commented
> `data->stats` should probably be called `data->ibf_statistics` or something like that?

sure i can do that in a follow up. What about `current_level_statistics`?

2021-11-29 14:46 UTC, eseiler approved these changes

2021-11-29 14:47 UTC, eseiler commented
> > `data->stats` should probably be called `data->ibf_statistics` or something like that?

> sure i can do that in a follow up. What about `current_level_statistics`? 

But there might be multiple ibfs on each level, and each one of them has their own statistics attached, no?

2021-11-29 14:47 UTC, merged