[MISC] Small refactoring of prefixes
seqan/chopper pull request #88
Opened 2021-12-09 11:37 UTC by smehringer

This will make it easier for raptor to parse layout files in case we decide to alter the look of the layout header.

2021-12-09 16:48 UTC, eseiler requested changes

2021-12-09 16:48 UTC, eseiler commented on include/chopper/layout/hierarchical_binning.hpp
> +                *data->output_buffer << prefix::header <<"FILES\tBIN_INDICES\tNUMBER_OF_BINS\tEST_MAX_TB_SIZES\tSCORE\tCORR\tT_MAX" << std::endl;
```suggestion
                *data->output_buffer << prefix::header << "FILES\tBIN_INDICES\tNUMBER_OF_BINS\tEST_MAX_TB_SIZES\tSCORE\tCORR\tT_MAX" << std::endl;
```

2021-12-09 16:48 UTC, eseiler commented on include/chopper/layout/hierarchical_binning.hpp
> +                *data->output_buffer << prefix::header <<"FILES\tBIN_INDICES\tNUMBER_OF_BINS" << std::endl;
```suggestion
                *data->output_buffer << prefix::header << "FILES\tBIN_INDICES\tNUMBER_OF_BINS" << std::endl;
```

2021-12-09 16:48 UTC, eseiler commented on include/chopper/prefixes.hpp
> +{
```suggestion
namespace chopper::prefix
{

```

2021-12-09 16:48 UTC, eseiler commented on include/chopper/prefixes.hpp
> +} // namespace chopper
```suggestion
} // namespace chopper::prefix
```

2021-12-09 16:48 UTC, eseiler commented on include/chopper/prefixes.hpp
> +constexpr std::string_view hibf{"HIGH_LEVEL_IBF"};
```suggestion
constexpr std::string_view high_level{"HIGH_LEVEL_IBF"};
```
?

2021-12-10 06:51 UTC, smehringer commented on src/chopper_layout.cpp
> +    fout << prefix::header << prefix::hibf << " max_bin_id:" << max_hibf_id << '\n';
```suggestion
    fout << prefix::header << prefix::high_level << " max_bin_id:" << max_hibf_id << '\n';
```

2021-12-13 10:26 UTC, eseiler approved these changes

2021-12-13 10:26 UTC, merged